export const REQUEST_VALIDATE_OWNERSHIP = 'REQUEST_VALIDATE_OWNERSHIP';
export const RECEIVE_VALIDATE_OWNERSHIP = 'RECEIVE_VALIDATE_OWNERSHIP';
export const ERROR_VALIDATE_OWNERSHIP = 'ERROR_VALIDATE_OWNERSHIP';
export const CLEAN_VALIDATE_OWNERSHIP = 'CLEAN_VALIDATE_OWNERSHIP';