export const REQUEST_VALIDATE_OWNERSHIP = 'REQUEST_VALIDATE_OWNERSHIP';
export const RECEIVE_VALIDATE_OWNERSHIP = 'RECEIVE_VALIDATE_OWNERSHIP';
export const ERROR_VALIDATE_OWNERSHIP = 'ERROR_VALIDATE_OWNERSHIP';
export const CLEAN_VALIDATE_OWNERSHIP = 'CLEAN_VALIDATE_OWNERSHIP';

export const REQUEST_CLAIM = 'REQUEST_CALIM';
export const RECEIVE_CLAIM = 'RECEIVE_CLAIM';
export const ERROR_CLAIM = 'ERROR_CLAIM';

export const REQUEST_TRANSFER_TO_REGISTRAR = 'REQUEST_TRANSFER_TO_REGISTRAR';
export const RECEIVE_TRANSFER_TO_REGISTRAR = 'RECEIVE_TRANSFER_TO_REGISTRAR';
export const ERROR_TRANSFER_TO_REGISTRAR = 'ERROR_TRANSFER_TO_REGISTRAR';
